type = "HinduCalendarEvent"
jsonClass = "HinduCalendarEvent"

name = "Dummy Festival for Pausha Shukla Navami"
description = "A test festival on Pausha Shukla Navami (9th tithi, 10th lunar month)."
observed_on = "tithi"
tags = ["Dummy", "Test", "Nepali"]

[rules]
tithi = 9
month = 10
paksha = "shukla"

[timing]
type = "HinduCalendarEventTiming"
jsonClass = "HinduCalendarEventTiming"
month_type = "lunar_month"
month_number = 10
anga_type = "tithi"
anga_number = 9
#kaala = "सूर्योदयः"

[details]
en = "Observed on Pausha Shukla Navami for testing."
ne = "पौष शुक्ल नवमीमा परीक्षण उत्सव।"
