type = "HinduCalendarEvent"
jsonClass = "HinduCalendarEvent"

name = "पौष शुक्ल द्वादशी"
description = "This is Dwadashi in Pausha Shukla Paksha."
observed_on = "tithi"
tags = ["Nepali", "Test"]

[rules]
tithi = 12
month = 10

[timing]
type = "HinduCalendarEventTiming"
jsonClass = "HinduCalendarEventTiming"
month_type = "lunar_month"
month_number = 10
anga_type = "tithi"
anga_number = 12
#kaala = "सूर्योदयः"

[details]
en = "Observed on Pausha Shukla Dwadashi."
ne = "पौष शुक्ल द्वादशीमा उत्सव।"
