type = "HinduCalendarEvent"
jsonClass = "HinduCalendarEvent"

name = "पौष शुक्ल त्रयोदशी"
description = "This is Trayodashi in Pausha Shukla Paksha."
observed_on = "tithi"
tags = ["Nepali", "Test"]

[rules]
tithi = 13
month = 10

[timing]
type = "HinduCalendarEventTiming"
jsonClass = "HinduCalendarEventTiming"
month_type = "lunar_month"
month_number = 10
anga_type = "tithi"
anga_number = 13
#kaala = "सूर्योदयः"

[details]
en = "Observed on Pausha Shukla Trayodashi."
ne = "पौष शुक्ल त्रयोदशीमा उत्सव।"
